# fly.toml app configuration file generated for watchme on 2023-08-21T22:36:37+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "watchme"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "sqlite"
  destination = "/app/db/sqlite"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
